### ISSUE TITLE
chore: 프로젝트 초기 설정

### ISSUE THREAD

**Issue by oreocube** [oreocube/our-balance-android#1]
## Description
- 프로젝트 초기 설정

## Task
- [x] 템플릿 설정
- [x] 라벨 설정
- [x] 프로젝트 생성
- [x] Kotlin DSL 적용
- [x] 멀티 모듈 적용
- [x] 기본 dependency 추가
