### ISSUE TITLE
ui: 메인화면 기본 UI 구현

### ISSUE THREAD

**Issue by oreocube** [oreocube/our-balance-android#21]
## Screen Type
- 메인화면

## Description
- 기본 메인 화면 UI 구현

## Task
- [x] 리스트 아이템 레이아웃 구현
- [x] 로그인 여부 체크
- [x] 메인화면 기본 레이아웃 구성
