### ISSUE TITLE
feat: 밸런스 리스트 조회 화면 구현

### ISSUE THREAD

**Issue by oreocube** [oreocube/our-balance-android#23]
## Screen Type
- 메인화면

## Description
- 리스트 조회 API 만으로 메인화면을 그릴 수 없어 로직 수정

## Task
- [x] BalanceDetail 모델, 매퍼 수정
- [x] 상세 조회 API 비동기 호출하도록 유스케이스 수정
- [x] 밸런스 리스트 화면 구현
