### ISSUE TITLE
feat: 로그인, 회원가입 기능 설계

### ISSUE THREAD

**Issue by oreocube** [oreocube/our-balance-android#5]
## Description
- 로그인, 회원가입 기능 구현

## Task
- [x] 도메인 레이어 Hilt 추가
- [x] Coroutines, DataStore dependency 추가
- [x] 데이터 모델 정의
- [x] 데이터 응답 추상화
- [x] datasource, repository 인터페이스 정의
